version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action/*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      webview-windows-bindings:
        patterns:
          - wry
          - webview2-com
          - windows
