name = "brick"
product-name = "Brick"
identifier = "dev.isogi.brick"
version = "0.3.1"
authors = ["Advance Raid Tools"]
publisher = "Advance"
description = "Advance Raid Tools"
long-description = "Small in-house updater for the Advance Raid Tools guild addon package."
homepage = "https://github.com/IsogiE/AdvanceRaidTools"
category = "Utility"
out-dir = "dist/packages"
binaries-dir = "target/release"
before-packaging-command = "cargo build --release"
binaries = [{ path = "brick", main = true }]
icons = ["src/assets/brick.ico", "src/assets/brick.png"]
formats = ["appimage"]

[linux]
generate-desktop-entry = true

[nsis]
installer-mode = "currentUser"
preinstall-section = '''
Section ForceCurrentUserSilentUpdateDir
  IfSilent 0 force_current_user_silent_update_dir_done
  StrCpy $INSTDIR "$LOCALAPPDATA\${PRODUCTNAME}"
force_current_user_silent_update_dir_done:
SectionEnd
'''
