FROM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS build
ENV CGO_ENABLED=0 GOTOOLCHAIN=local
WORKDIR /build
COPY proxy/go.mod proxy/go.sum ./
RUN go mod download && go mod verify
COPY proxy/main.go ./
RUN go build -mod=readonly -trimpath -ldflags="-s -w" -o /build/caddy .

FROM caddy:2-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
RUN apk upgrade --no-cache
COPY --from=build /build/caddy /usr/bin/caddy
